export { default as courseEditHeader } from "./course-edit-header.vue"
export { default as courseEditType } from "./course-edit-type.vue"
export { default as courseNewBlock } from "./course-new-block.vue"
export { default as courseEditNav } from "./course-edit-nav.vue"
export { default as courseRename } from "./course-rename.vue"