export { default as LayaScMc } from "./laya-la-scmc"
//export { default as LayaQuizSort } from "./laya-la-sort"
export { default as LayaQuizDragDrop } from "./laya-la-drag-drop"
export { default as LayaQuizRelate } from "./laya-la-relate"

export { default as LayaDialog } from "./laya-lb-dialog"
export { default as LayaPlyrVimeo } from "./laya-lb-plyr-vimeo"
export { default as LayaAbleplayer } from "./misc/laya-ableplayer"
//export { default as LayaPlyr } from "./misc/laya-plyr"
//export { default as LayaStepper } from "./misc/laya-stepper"
export { default as LayaAudioInline } from "./misc/laya-audio-inline"
export { default as LayaHtml } from "./misc/laya-html"
export { default as LayaCourseTable } from "./misc/laya-course-table"
